language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: hStsuqxSxPbmJr5KzR1qcwxPeHtdv58nCHRlCQidrYWTf+i4odGHlmopW3gyHqiaB1eqqWUKwXUlpx3RAr9Pcz5mdcsokfDyLbBY+hELL2C0zoTPIQwuQ9BvkO0QsAnW0j2F43Mct8hPlq1Utw8ds2q8w63dHr005xu6oE/elcM=
  app: madbomber
  on:
    repo: MadBomber/madbomber
